# Generated by Django 3.2.8 on 2021-10-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_auto_20211012_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineday',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
