# Generated by Django 3.2.8 on 2021-10-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0005_routineday_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineweek',
            name='routine',
        ),
        migrations.RemoveField(
            model_name='routineday',
            name='date',
        ),
        migrations.RemoveField(
            model_name='routineday',
            name='number',
        ),
        migrations.RemoveField(
            model_name='routineday',
            name='routine_week',
        ),
        migrations.AddField(
            model_name='routineday',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='routineday',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
        migrations.DeleteModel(
            name='RoutineWeek',
        ),
    ]
