# Generated by Django 3.2.8 on 2021-10-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0006_auto_20211012_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoutineDay',
            new_name='Workout',
        ),
        migrations.RenameField(
            model_name='routineitem',
            old_name='routine_day',
            new_name='workout',
        ),
    ]
