# Generated by Django 3.2.8 on 2021-10-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0007_auto_20211012_2006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoutineItem',
            new_name='WorkoutItem',
        ),
    ]
