# Generated by Django 3.2.8 on 2021-10-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0008_rename_routineitem_workoutitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutitem',
            name='muscle_group',
        ),
    ]
