# Generated by Django 3.2.8 on 2021-10-14 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0011_workout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutitem',
            name='muscle_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.musclegroup'),
        ),
    ]
