# Generated by Django 3.2.8 on 2021-10-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0012_workoutitem_muscle_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutitem',
            options={'ordering': ['muscle_group']},
        ),
    ]
