# Generated by Django 3.2.8 on 2021-10-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0013_alter_workoutitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutitem',
            options={},
        ),
    ]
