# Generated by Django 3.2.8 on 2021-10-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0014_alter_workoutitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CycleType',
        ),
        migrations.AlterField(
            model_name='workout',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
