# Generated by Django 3.2.8 on 2021-10-21 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0015_auto_20211021_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.exercise')),
                ('muscle_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.musclegroup')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.workout')),
            ],
        ),
        migrations.DeleteModel(
            name='Readiness',
        ),
    ]
