# Generated by Django 3.2.8 on 2021-10-22 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0017_workoutexerciseset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadinessChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Lowest'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Highest')])),
                ('readiness_checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.readinesschecklist')),
                ('workout', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.workout')),
            ],
        ),
    ]
