# Generated by Django 3.2.8 on 2021-10-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0018_readinesschecklist_workoutreadiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutreadiness',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Lowest'), (2, 'Lower'), (3, 'Medium'), (4, 'Higher'), (5, 'Highest')]),
        ),
    ]
