# Generated by Django 3.2.8 on 2021-10-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0019_alter_workoutreadiness_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
