# Generated by Django 3.2.8 on 2021-10-25 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0020_auto_20211025_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutreadiness',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.workout'),
        ),
    ]
