# Generated by Django 3.2.8 on 2021-10-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0021_alter_workoutreadiness_workout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadinessChecklist',
            new_name='ReadinessQuestion',
        ),
    ]
