# Generated by Django 3.2.8 on 2021-10-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0022_rename_readinesschecklist_readinessquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutreadiness',
            old_name='readiness_checklist',
            new_name='readiness_question',
        ),
    ]
