# Generated by Django 3.2.8 on 2021-10-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0023_rename_readiness_checklist_workoutreadiness_readiness_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutreadiness',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.workout'),
        ),
    ]
