# Generated by Django 3.2.8 on 2021-10-26 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0024_alter_workoutreadiness_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutreadiness',
            name='readiness_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.readinessquestion'),
        ),
    ]
