# Generated by Django 3.2.8 on 2021-10-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0025_alter_workoutreadiness_readiness_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
