# Generated by Django 3.2.8 on 2021-11-09 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_exercise_tier'),
        ('routines', '0028_alter_workoutreadiness_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='muscle_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.musclegroup'),
        ),
        migrations.AlterField(
            model_name='workoutitem',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='workoutitem',
            name='muscle_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.musclegroup'),
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='MuscleGroup',
        ),
    ]
