# Generated by Django 3.2.8 on 2021-11-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0029_auto_20211109_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutReadiness',
            new_name='Readiness',
        ),
    ]
