# Generated by Django 3.2.8 on 2021-11-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0030_rename_workoutreadiness_readiness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readiness',
            name='workout',
        ),
        migrations.AddField(
            model_name='readiness',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
