# Generated by Django 3.2.8 on 2021-11-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0031_auto_20211130_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='readiness',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.readiness'),
        ),
    ]
