# Generated by Django 3.2.8 on 2021-11-30 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0032_workout_readiness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readiness',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='readiness',
            name='readiness_question',
        ),
        migrations.CreateModel(
            name='ReadinessAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Poorest'), (2, 'Poorer'), (3, 'Medium'), (4, 'Better'), (5, 'Best')])),
                ('readiness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.readiness')),
                ('readiness_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.readinessquestion')),
            ],
        ),
    ]
