# Generated by Django 3.2.8 on 2021-11-30 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routines', '0033_auto_20211130_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='readiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readiness', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readinessanswer',
            name='readiness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.readiness'),
        ),
        migrations.AlterField(
            model_name='readinessanswer',
            name='readiness_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.readinessquestion'),
        ),
    ]
