# Generated by Django 3.2.8 on 2021-12-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0035_auto_20211202_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='is_set_adjust',
            field=models.BooleanField(default=0),
        ),
    ]
