# Generated by Django 3.2.8 on 2022-01-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0036_workout_is_set_adjust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='is_set_adjust',
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='is_set_adjust',
            field=models.BooleanField(default=0),
        ),
        migrations.DeleteModel(
            name='WorkoutItem',
        ),
    ]
