# Generated by Django 3.2.8 on 2022-01-29 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0038_alter_readiness_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexerciseset',
            name='rir',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
