# Generated by Django 3.2.8 on 2022-02-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0039_alter_workoutexerciseset_rir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='muscle_group',
        ),
    ]
