# Generated by Django 3.2.8 on 2022-02-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0040_remove_workoutexercise_muscle_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='generate_sets',
            field=models.BooleanField(default=0),
        ),
    ]
