# Generated by Django 3.2.8 on 2022-02-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0041_workoutexercise_generate_sets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutexercise',
            old_name='generate_sets',
            new_name='is_set_generate',
        ),
    ]
