# Generated by Django 3.2.8 on 2022-02-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0043_workout_is_exercise_generate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
