# Generated by Django 3.2.8 on 2022-02-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_trainingsplitday'),
        ('routines', '0044_auto_20220216_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='training_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.trainingsplitday'),
        ),
    ]
