# Generated by Django 3.2.8 on 2022-02-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0045_workout_training_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='training_day',
            new_name='split_day',
        ),
    ]
