# Generated by Django 3.2.8 on 2022-01-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211130_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Periodization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='trainingphase',
            name='max_reps',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trainingphase',
            name='max_rir',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trainingphase',
            name='min_reps',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trainingphase',
            name='min_rir',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
