# Generated by Django 3.2.8 on 2022-01-28 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220127_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMetrics',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='training_days',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
