# Generated by Django 3.2.8 on 2022-01-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220128_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingPhase',
            new_name='TrainingFocus',
        ),
    ]
