# Generated by Django 3.2.8 on 2022-02-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_userrm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingfocus',
            name='max_reps',
        ),
        migrations.RemoveField(
            model_name='trainingfocus',
            name='max_rir',
        ),
        migrations.RemoveField(
            model_name='trainingfocus',
            name='min_reps',
        ),
        migrations.RemoveField(
            model_name='trainingfocus',
            name='min_rir',
        ),
    ]
