# Generated by Django 3.2.8 on 2022-02-13 15:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220201_1232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frequency',
            new_name='TrainingSplit',
        ),
        migrations.CreateModel(
            name='FrequencyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('hierarchy', models.PositiveIntegerField()),
                ('trainiing_split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trainingsplit')),
                ('training_focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trainingfocus')),
            ],
        ),
    ]
