# Generated by Django 3.2.8 on 2022-02-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220213_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequencyallocation',
            old_name='trainiing_split',
            new_name='training_split',
        ),
    ]
