# Generated by Django 3.2.8 on 2022-02-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_trainiing_split_frequencyallocation_training_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='training_split',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.trainingsplit'),
        ),
    ]
