# Generated by Django 3.2.8 on 2022-02-19 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_trainingsplitday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsplitday',
            name='training_split',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trainingsplit'),
        ),
    ]
