# Generated by Django 3.2.8 on 2022-02-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_trainingsplitday_training_split'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSplitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trainingsplitday')),
                ('this_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='this_day', to='accounts.trainingsplitday')),
            ],
        ),
    ]
