# Generated by Django 3.2.8 on 2022-02-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0033_remove_force_training_day'),
        ('accounts', '0016_trainingsplitday_force'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsplitday',
            name='force',
            field=models.ManyToManyField(to='exercises.Force'),
        ),
        migrations.CreateModel(
            name='TrainingSplitDayForce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy', models.PositiveIntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trainingsplitday')),
                ('force', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.force')),
            ],
        ),
    ]
