# Generated by Django 3.2.8 on 2022-02-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_trainingsplititem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsplitday',
            name='training_split',
        ),
        migrations.AddField(
            model_name='trainingsplitday',
            name='training_split_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.trainingsplititem'),
        ),
    ]
