# Generated by Django 3.2.8 on 2022-02-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20220222_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsplitday',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
