# Generated by Django 3.2.8 on 2022-02-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_trainingsplitday_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingSplitOrder',
        ),
    ]
