# Generated by Django 3.2.8 on 2022-02-22 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_delete_trainingsplitorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsplitday',
            name='training_split_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trainingsplititem'),
        ),
    ]
