# Generated by Django 3.2.8 on 2022-02-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20220224_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingSplitItem',
            new_name='SplitItem',
        ),
        migrations.RenameField(
            model_name='trainingsplitday',
            old_name='training_split_item',
            new_name='split_item',
        ),
    ]
