# Generated by Django 3.2.8 on 2022-02-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0045_workout_training_day'),
        ('exercises', '0035_auto_20220223_1439'),
        ('accounts', '0027_auto_20220224_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingSplitDay',
            new_name='SplitDay',
        ),
    ]
