# Generated by Django 3.2.8 on 2022-02-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0035_auto_20220223_1439'),
        ('accounts', '0028_rename_trainingsplitday_splitday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingSplitDayForce',
            new_name='SplitDayForce',
        ),
    ]
