# Generated by Django 3.2.8 on 2021-11-09 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('purpose', models.CharField(choices=[('Squat', 'Squat'), ('Bench', 'Bench'), ('Deadlift', 'Deadlift')], help_text='Which main exercise does this improve?', max_length=60)),
                ('tier', models.CharField(choices=[('T2', 'T2'), ('T3', 'T3'), ('Other', 'Other')], help_text='T2 exercises are close variations of the main lifts,             T3 exercises develop the musculature eg. quads for squats,             Other exercises develop supplementary muscles', max_length=60)),
                ('mechanic', models.CharField(choices=[('Compound', 'Compound'), ('Isolation', 'Isolation')], max_length=60)),
                ('force', models.CharField(choices=[('Push', 'Push'), ('Pull', 'Pull')], max_length=60)),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.musclegroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
