# Generated by Django 3.2.8 on 2021-11-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='UserUniqueExercise'),
        ),
    ]
