# Generated by Django 3.2.8 on 2021-11-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_useruniqueexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='tier',
            field=models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('Other', 'Other')], help_text='T1 exercises are the competition exercises            T2 exercises are close variations of the main lifts,             T3 exercises develop the musculature eg. quads for squats,             Other exercises develop supplementary muscles', max_length=60),
        ),
    ]
