# Generated by Django 3.2.8 on 2022-01-27 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_exercisevolume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Force',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='muscle_group',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='tier',
        ),
        migrations.AddField(
            model_name='exercise',
            name='plpurpose',
            field=models.CharField(choices=[('Squat', 'Squat'), ('Bench', 'Bench'), ('Deadlift', 'Deadlift')], help_text='Which powerlifting exercise does this improve?', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='pltier',
            field=models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('Other', 'Other')], help_text='T1 exercises are the competition exercises.            T2 exercises are close variations of the main lifts.             T3 exercises develop the musculature eg. quads for squats.             Other exercises develop supplementary muscles', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='force',
            field=models.ManyToManyField(to='exercises.Force'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='force',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.force'),
        ),
    ]
