# Generated by Django 3.2.8 on 2022-02-01 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_rir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='plpurpose',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='pltier',
        ),
        migrations.CreateModel(
            name='ProgressionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('force', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.force')),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.mechanic')),
                ('purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.purpose')),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.tier')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='progression_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.progressiontype'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='purpose',
            field=models.ForeignKey(help_text='Which powerlifting exercise does this improve?', null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.purpose'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='tier',
            field=models.ForeignKey(help_text='T1 exercises are the competition exercises.            T2 exercises are close variations of the main lifts.             T3 exercises develop the musculature eg. quads for squats.             Other exercises develop supplementary muscles', null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.tier'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='mechanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.mechanic'),
        ),
    ]
