# Generated by Django 3.2.8 on 2022-02-01 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_userrm'),
        ('exercises', '0012_auto_20220201_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressiontype',
            name='training_focus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.trainingfocus'),
        ),
    ]
