# Generated by Django 3.2.8 on 2022-02-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_auto_20220201_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressiontype',
            name='purpose',
        ),
    ]
