# Generated by Django 3.2.8 on 2022-02-01 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0017_remove_progressiontype_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='progression_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.progressiontype'),
        ),
    ]
