# Generated by Django 3.2.8 on 2022-02-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0019_auto_20220201_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressiontype',
            name='force',
        ),
    ]
