# Generated by Django 3.2.8 on 2022-02-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0021_auto_20220204_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='isolation',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
