# Generated by Django 3.2.8 on 2022-02-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0022_exercise_isolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressiontype',
            name='min_rir',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
