# Generated by Django 3.2.8 on 2022-02-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0024_progression'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='force',
            name='base_weekly_sets',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
