# Generated by Django 3.2.8 on 2022-02-14 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_training_split'),
        ('exercises', '0027_remove_exercise_isolation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressiontype',
            name='mechanic',
        ),
        migrations.RemoveField(
            model_name='progressiontype',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='progressiontype',
            name='training_focus',
        ),
        migrations.AddField(
            model_name='exercise',
            name='max_reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='min_reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.purpose'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.tier'),
        ),
        migrations.CreateModel(
            name='ProgressionTypeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.mechanic')),
                ('progression_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.progressiontype')),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.tier')),
                ('training_focus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.trainingfocus')),
            ],
        ),
    ]
