# Generated by Django 3.2.8 on 2022-02-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0028_auto_20220214_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressiontype',
            name='max_reps',
        ),
        migrations.RemoveField(
            model_name='progressiontype',
            name='min_reps',
        ),
        migrations.RemoveField(
            model_name='progressiontype',
            name='min_rir',
        ),
        migrations.RemoveField(
            model_name='progressiontype',
            name='target_rir',
        ),
        migrations.AddField(
            model_name='progressiontypeallocation',
            name='max_reps',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='progressiontypeallocation',
            name='min_reps',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='progressiontypeallocation',
            name='min_rir',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='progressiontypeallocation',
            name='target_rir',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
