# Generated by Django 3.2.8 on 2022-02-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_trainingsplitday'),
        ('exercises', '0029_auto_20220214_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='force',
            name='category',
        ),
        migrations.AddField(
            model_name='force',
            name='training_day',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.TrainingSplitDay'),
        ),
        migrations.DeleteModel(
            name='ForceCategory',
        ),
    ]
