# Generated by Django 3.2.8 on 2022-02-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_trainingsplitday'),
        ('exercises', '0030_auto_20220219_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='force',
            name='training_day',
            field=models.ManyToManyField(blank=True, to='accounts.TrainingSplitDay'),
        ),
    ]
