# Generated by Django 3.2.8 on 2022-02-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0031_alter_force_training_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_unilateral',
            field=models.BooleanField(default=0),
        ),
    ]
