# Generated by Django 3.2.8 on 2022-02-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0032_exercise_is_unilateral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='force',
            name='training_day',
        ),
    ]
