# Generated by Django 3.2.8 on 2022-02-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0034_progression_uniquecheck'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='progression',
            name='UniqueCheck',
        ),
        migrations.AddConstraint(
            model_name='progression',
            constraint=models.UniqueConstraint(fields=('progression_type', 'rep_delta', 'rir_delta'), name='UniqueProgressionCheck'),
        ),
        migrations.AddConstraint(
            model_name='progressiontypeallocation',
            constraint=models.UniqueConstraint(fields=('training_focus', 'mechanic', 'tier'), name='UniqueProgressionTypeCheck'),
        ),
    ]
