# Generated by Django 3.2.8 on 2022-03-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0035_auto_20220223_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='hierarchy',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
