# Generated by Django 3.2.8 on 2022-03-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0036_tier_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='hierarchy',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
