# Generated by Django 3.2.8 on 2022-03-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0037_alter_tier_hierarchy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tier',
            options={'ordering': ['hierarchy']},
        ),
    ]
