# Generated by Django 3.2.8 on 2022-06-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0038_alter_tier_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='progression',
            name='UniqueProgressionCheck',
        ),
        migrations.RemoveConstraint(
            model_name='progressiontypeallocation',
            name='UniqueProgressionTypeCheck',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='progression_type',
        ),
    ]
