# Generated by Django 3.2.8 on 2022-06-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0039_auto_20220609_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressiontypeallocation',
            name='mechanic',
        ),
        migrations.RemoveField(
            model_name='progressiontypeallocation',
            name='progression_type',
        ),
        migrations.RemoveField(
            model_name='progressiontypeallocation',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='progressiontypeallocation',
            name='training_focus',
        ),
        migrations.DeleteModel(
            name='Progression',
        ),
        migrations.DeleteModel(
            name='ProgressionType',
        ),
        migrations.DeleteModel(
            name='ProgressionTypeAllocation',
        ),
    ]
