# Generated by Django 3.2.8 on 2022-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0041_auto_20220610_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
    ]
