# Generated by Django 3.2.8 on 2022-06-10 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_rename_trainingsplitdayforce_splitdayforce'),
        ('exercises', '0042_progressiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionTypeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_reps', models.PositiveIntegerField(null=True)),
                ('max_reps', models.PositiveIntegerField(null=True)),
                ('target_rir', models.PositiveIntegerField(null=True)),
                ('min_rir', models.PositiveIntegerField(default=1, null=True)),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.mechanic')),
                ('progression_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.progressiontype')),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.tier')),
                ('training_focus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.trainingfocus')),
            ],
        ),
        migrations.AddConstraint(
            model_name='progressiontypeallocation',
            constraint=models.UniqueConstraint(fields=('training_focus', 'mechanic', 'tier'), name='UniqueProgressionTypeCheck'),
        ),
    ]
