# Generated by Django 3.2.8 on 2022-06-10 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0043_auto_20220610_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressiontypeallocation',
            name='target_rir',
        ),
        migrations.AddField(
            model_name='progressiontypeallocation',
            name='max_rir',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='progressiontypeallocation',
            name='max_reps',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='progressiontypeallocation',
            name='min_reps',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='progressiontypeallocation',
            name='min_rir',
            field=models.PositiveIntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
