# Generated by Django 3.2.8 on 2022-06-11 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0045_exercise_progression_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_delta', models.IntegerField()),
                ('rir_delta', models.IntegerField()),
                ('weight_change', models.FloatField(blank=True, null=True)),
                ('rep_change', models.IntegerField(blank=True, null=True)),
                ('rir_change', models.IntegerField(blank=True, null=True)),
                ('progression_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.progressiontype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='progression',
            constraint=models.UniqueConstraint(fields=('progression_type', 'rep_delta', 'rir_delta'), name='UniqueProgressionCheck'),
        ),
    ]
